name: main

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: lgeiger/black-action@v1.0.1
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_options: '--no-verify --signoff'
        file_pattern: .
        repository: .
