name: main

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: testing
      run: echo test
    - uses: fish895623/android-sdk-action@master
      id: hello
      with:
        who-to-greet: 'Mo helloj?'
    - name: Get output
      run: echo "${{ steps.hello.outputs.time }}"
